### PR TITLE
macOS Port

### PR DESCRIPTION
**Pull request by sandiz**
macOS port of RocksnifferLib

Motivation:
I wanted the rocksmith live feature of my [application](https://github.com/sandiz/rs-manager) to work on mac (uses rocksniffer underneath so it works on windows already)

Highlights:
* add macOS api library
* song id/timer pointer chain
* add support for native pointer scanning for note data
* add support for sniffing file handles opened 

Notes:
1. Since, Cheat Engine for Mac has no pointer scanning support atm, I used Bit-Slicer to find the pointer chains. Bit-Slicer pointer scan support is rudimentary and gave many false positives.So far,  I've managed to find static pointers for song id and song timer. For note data, i search the memory for 111000 (got the idea from your latest commits) and then read it from there
2. Requires mono and elevated privileges on mac

Screenshots:
* debugMemoryReadout 

image

* sample jsonResponse from Addon  [resp.json](https://gist.github.com/sandiz/535ebe97d65039ffb004fb3e19551e2c)

* sniffFileHandles
image

Open to all feedback!

### CODE REVIEW

**Comment by kokolihapihvi** [comment]
Hey, sorry for the long wait!

Thanks for the PR!
I currently don't own any mac OS devices and would be unable to maintain/build/test for mac, would you be interested in maintaining this branch?

Is this just the library, modified to work on mac OS, or does it also require changes on the RockSniffer application?

**Comment by sandiz** [comment]
hi!
> would you be interested in maintaining this branch?

certainly, i can maintain/build/fix bugs

>Is this just the library, modified to work on mac OS, or does it also require changes on the RockSniffer application?

just the library, RockSniffer should work unmodified

**Comment by kokolihapihvi** [comment]
Hey,
I'll go ahead and merge this and see if I can give you push permission to the macos branch directly.

I'd also love to talk to you on discord or something since we work on very similar things, would be interesting to share some thoughts!

**Comment by sandiz** [comment]
thanks! got the invite!

i am in r/rocksmith discord channel nick: `0zymandias`, maybe we can have #tools channel going there or something 😄

**Pull request merged**
